---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-db-influx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/stock-db-influx.git
    targetRevision: main
    path: charts/stock-db-influx
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
