---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: default

labels:
  - includeSelectors: true
    pairs:
      app: stock-db-influx

images:
  - name: stock-db-influx
    newName: stock-db-influx
    newTag: latest
